# A modified config which pulls pages from every site which Crom tracks.

output-path = "results-all.json"
save-page-offset = "1000"
sites = [
    "scp-wiki",
    "scp-int",
    "scp-wiki-cn",
    "fondationscp", # FR
    "scp-ru",
    "scp-pl",
    "lafundacionscp", # ES
    "scp-jp",
    "scpko",
    "scp-th",
    "scp-wiki-de",
    "fondazionescp", # IT
    "scp-ukrainian",
    "scp-pt-br",
    "scp-cs",
    "scp-zh-tr",
    "scp-un",
    "scp-el",
    "scp-idn",
    "scp-nd",
    "scpvakfi", # TR
    "scp-vn",

    "wanderers-library",
    "wanderers-library-cs",
    "wanderers-library-jp",
    "wanderers-library-ko",
    "wanderers-library-pl",

    "backrooms-wiki",
    "backrooms-vn",
    "pl-backrooms-wiki",
    "backrooms-wiki-cn",
    "fr-backrooms-wiki",
    "ru-backrooms-wiki",
    "pt-br-backrooms-wiki",
    "es-backrooms-wiki",
    "japan-backrooms-wiki",
    "it-backrooms-wiki",
    "de-backrooms-wiki",
]
